main/urls.py
from django.urls import path
from .views import index, create_request, view_requests, delete_request, check_username, change_status
from .views import BBLoginView
from .views import profile
from .views import BBLogoutView
from .views import ChangeUserInfoView
from .views import BBPasswordChangeView
from .views import RegisterDoneView, RegisterUserView
from .views import DeleteUserView
from . import views
app_name = 'main'

urlpatterns = [
   path('', index, name='index'),
   path('accounts/login', BBLoginView.as_view(), name='login'),
   path('accounts/profile/', profile, name='profile'),
   path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
   path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
   path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
   path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
   path('accounts/register/', RegisterUserView.as_view(), name='register'),
   path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
   path('create/', create_request, name='create_request'),
   path('requests/', view_requests, name='view_requests'),
   path('delete/<int:request_id>/', delete_request, name='delete_request'),
   path('check_username/', views.check_username, name='check_username'),
   path('requests/change_status/<int:request_id>/', change_status, name='change_status'),
   path('manage_categories/', views.manage_categories, name='manage_categories'),
   path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import Signal
from .validations import validate_image

user_registrated = Signal(['instance'])

class AdvUser(AbstractUser):
   is_activated = models.BooleanField(default=True, db_index=True,verbose_name='Прошел активацию?')
   fio = models.CharField(max_length=100, blank=True, verbose_name='ФИО')
   class Meta(AbstractUser.Meta):
       pass




class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Категория', unique=True)

    def __str__(self):
        return self.name

class CreateRequest(models.Model):
    STATUS_CHOICES = (
        ('new', 'Новая'),
        ('in_progress', 'Принято в работу'),
        ('completed', 'Выполнено'),
    )
    user = models.ForeignKey(AdvUser, on_delete=models.CASCADE, verbose_name='Пользователь')
    title = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото помещения', blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Временная метка')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new', verbose_name='Статус')
    design_image = models.ImageField(upload_to='designs/%Y/%m/%d/', verbose_name='Изображение дизайна', blank=True,null=True)
    comment = models.TextField(verbose_name='Комментарий', blank=True, null=True)
    def __str__(self):
        return self.title

main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .models import user_registrated, AdvUser
import re
from .models import CreateRequest, Category


class ChangeUserInfoForm(forms.ModelForm):
   email = forms.EmailField(required=True, label='Адрес электронной почты')

   class Meta:
       model = AdvUser
       fields = ('username', 'email', 'fio')

class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput,help_text=password_validation.password_validators_help_text_html()
    )
    password2 = forms.CharField(
        label='Пароль (повторно)',
        widget=forms.PasswordInput,help_text='Повторите тот же самый пароль еще раз'
    )
    fio = forms.CharField(label='ФИО', max_length=100)
    username = forms.CharField(label='Логин', max_length=30)
    consent = forms.BooleanField(label='Согласие на обработку персональных данных')

    def clean_fio(self):
        fio = self.cleaned_data.get('fio')
        valid_characters = "^[А-яЁё -]{1,}$" # /- не используется в питоне

        if not re.match(valid_characters, fio):
            raise ValidationError('ФИО может содержать только кириллические буквы, пробелы и дефисы.')

        if not re.match(valid_characters, fio):
            raise ValidationError('ФИО должно содержать хотя бы одну кириллическую букву.')

        return fio


    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            self.add_error('password2', ValidationError(
                'Введенные пароли не совпадают.'
            ))

    def clean_consent(self):
        consent = self.cleaned_data.get('consent')
        if not consent:
            raise ValidationError('Необходимо дать согласие на обработку персональных данных.')
        return consent

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        user.is_activated = True
        if commit:
            user.save()
            # Отправка сигнала о регистрации пользователя
            user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'fio', 'email', 'password1', 'password2', 'consent')


class CreateRequestForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label=None, label='Категория')
    photo = forms.ImageField(label='Фото помещения', required=False)

    class Meta:
        model = CreateRequest
        fields = ['title', 'description', 'category', 'photo']

    def clean_photo(self):
        photo = self.cleaned_data.get('photo')
        if photo:
            if photo.size > 2 * 1024 * 1024:  # 2MB
                raise ValidationError('Размер файла превышает 2Мб.')
            if photo.image.format.lower() not in ['jpeg', 'jpg', 'png', 'bmp']:
                raise ValidationError('Неподдерживаемый формат файла. Допустимые форматы: JPG, JPEG, PNG, BMP.')
        return photo

class ChangeStatusForm(forms.ModelForm):
    class Meta:
        model = CreateRequest
        fields = ['status', 'design_image', 'comment']

    def __init__(self, *args, **kwargs):
        super(ChangeStatusForm, self).__init__(*args, **kwargs)
        # Ограничиваем выбор статусов только для "Выполнено" и "Принято в работу"
        self.fields['status'].choices = [
            ('completed', 'Выполнено'),
            ('in_progress', 'Принято в работу'),
        ]
        # Делаем поле design_image обязательным только для статуса "Выполнено"
        if self.instance.status == 'completed':
            self.fields['design_image'].required = True
        else:
            self.fields['design_image'].required = False
        # Делаем поле comment обязательным только для статуса "Принято в работу"
        if self.instance.status == 'in_progress':
            self.fields['comment'].required = True
        else:
            self.fields['comment'].required = False



class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

main/views.py
from urllib.request import Request

from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy


from .forms import ChangeUserInfoForm, ChangeStatusForm, CategoryForm
from .models import AdvUser, Category
from django.contrib.auth.views import PasswordChangeView
from .forms import RegisterUserForm
from django.views.generic import UpdateView, CreateView, TemplateView, DeleteView

from .forms import CreateRequestForm
from .models import CreateRequest
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.core.exceptions import ObjectDoesNotExist

def index(request):
    completed_requests = CreateRequest.objects.filter(status='completed').order_by('-timestamp')[:4]
    in_progress_count = CreateRequest.objects.filter(status='in_progress').count()
    context = {
        'completed_requests': completed_requests,
        'in_progress_count': in_progress_count,
    }
    return render(request, 'main/index.html', context)

@login_required
def profile(request):
   return render(request, 'main/profile.html')


class BBLoginView(LoginView):
   template_name = 'main/login.html'


class BBLogoutView(LoginRequiredMixin, LogoutView):
   template_name = 'main/logout.html'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin,UpdateView):
   model = AdvUser
   template_name = 'main/change_user_info.html'
   form_class = ChangeUserInfoForm
   success_url = reverse_lazy('main:profile')
   success_message = 'Личные данные пользователя изменены'


   def dispatch(self, request, *args, **kwargs):
       self.user_id = request.user.pk
       return super().dispatch(request, *args, **kwargs)


   def get_object(self, queryset=None):
       if not queryset:
           queryset = self.get_queryset()
       return get_object_or_404(queryset, pk=self.user_id)


class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
   template_name = 'main/password_change.html'
   success_url = reverse_lazy('main:profile')
   success_message = 'Пароль пользователя изменен'



class RegisterUserView(CreateView):
   model = AdvUser
   template_name = 'main/register_user.html'
   form_class = RegisterUserForm
   success_url = reverse_lazy('main:register_done')

class RegisterDoneView(TemplateView):
   template_name = 'main/register_done.html'

class DeleteUserView(LoginRequiredMixin, DeleteView):
   model = AdvUser
   template_name = 'main/delete_user.html'
   success_url = reverse_lazy('main:index')

   def dispatch(self, request, *args, **kwargs):
       self.user_id = request.user.pk
       return super().dispatch(request, *args, **kwargs)

   def post(self, request, *args, **kwargs):
       logout(request)
       messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
       return super().post(request, *args, **kwargs)

   def get_object(self, queryset=None):
       if not queryset:
           queryset = self.get_queryset()
       return get_object_or_404(queryset, pk=self.user_id)

@login_required
def view_requests(request):
    if request.user.is_staff:
        requests = CreateRequest.objects.all()
    else:
        requests = CreateRequest.objects.filter(user=request.user)

    if request.method == 'POST':
        request_id = request.POST.get('request_id')
        request_obj = get_object_or_404(CreateRequest, id=request_id)
        form = ChangeStatusForm(request.POST, request.FILES, instance=request_obj)
        if form.is_valid():
            form.save()
            return redirect('main:view_requests')
    else:
        form = ChangeStatusForm()

    return render(request, 'main/view_requests.html', {'requests': requests, 'form': form})

@login_required
def create_request(request):
    # Проверка на количество заявок со статусом "Новая"
    if CreateRequest.objects.filter(user=request.user, status='new').count() >= 3:
        messages.error(request, 'Вы достигли лимита заявок со статусом "Новая". Пожалуйста, дождитесь, пока одна из ваших заявок не будет обработана.')
        return render(request, 'main/create_request.html', {'form': None})

    if request.method == 'POST':
        form = CreateRequestForm(request.POST, request.FILES)
        if form.is_valid():
            # Проверка на наличие заявки с той же категорией и статусом "Новая"
            category = form.cleaned_data['category']
            if CreateRequest.objects.filter(user=request.user, category=category, status='new').exists():
                messages.error(request, 'У вас уже есть заявка с этой категорией со статусом "Новая".')
                return redirect('main:create_request')

            request_obj = form.save(commit=False)
            request_obj.user = request.user
            request_obj.save()
            return redirect('main:view_requests')
    else:
        form = CreateRequestForm()
    return render(request, 'main/create_request.html', {'form': form})


#метод для удаления заявки
@login_required
def delete_request(request, request_id):
    request_obj = get_object_or_404(CreateRequest, id=request_id)

    # Проверка, что пользователь может удалить заявку
    if request.user != request_obj.user:
        messages.error(request, 'Вы не можете удалить эту заявку.')
        return redirect('main:view_requests')

    # Проверка, что статус заявки не "Принято в работу" или "Выполнено"
    if request_obj.status in ['in_progress', 'completed']:
        messages.error(request, 'Вы не можете удалить заявку со статусом "Принято в работу" или "Выполнено".')
        return redirect('main:view_requests')

    if request.method == 'POST':
        request_obj.delete()
        messages.success(request, 'Заявка успешно удалена.')
        return redirect('main:view_requests')

    return render(request, 'main/delete_request.html', {'request_obj': request_obj})



@require_POST
def check_username(request):
    response_data = {}
    username = request.POST.get("username")
    user = None
    try:
        user = AdvUser.objects.get(username=username)
    except ObjectDoesNotExist:
        pass
    except Exception as e:
        raise e

    if user:
        response_data["exists"] = True
        response_data["message"] = "Пользователь с таким логином уже существует."
    else:
        response_data["exists"] = False

    return JsonResponse(response_data)

@user_passes_test(lambda u: u.is_staff)
@login_required
def change_status(request, request_id):
    request_obj = get_object_or_404(CreateRequest, id=request_id)

    if request_obj.status == 'completed':
        messages.error(request, 'Редактирование заявки с статусом "Выполнено" невозможно.')
        return redirect('main:view_requests')

    if request.method == 'POST':
        form = ChangeStatusForm(request.POST, request.FILES, instance=request_obj)
        if form.is_valid():
            form.save()
            messages.success(request, 'Заявка успешно отредактирована.')
            return redirect('main:view_requests')
    else:
        form = ChangeStatusForm(instance=request_obj)

    return render(request, 'main/change_status.html', {'form': form, 'request_obj': request_obj})




@login_required
def manage_categories(request):
    if not request.user.is_staff:
        return redirect('main:index')

    categories = Category.objects.all()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Категория успешно добавлена.')
            return redirect('main:manage_categories')
    else:
        form = CategoryForm()

    return render(request, 'main/manage_categories.html', {'categories': categories, 'form': form})

@login_required
def delete_category(request, category_id):
    if not request.user.is_staff:
        return redirect('main:index')

    category = get_object_or_404(Category, id=category_id)
    CreateRequest.objects.filter(category=category).delete()  # Правильное использование менеджера объектов
    category.delete()
    messages.success(request, 'Категория и все связанные заявки успешно удалены.')
    return redirect('main:manage_categories')

def request_list(request):
    categories = Category.objects.all()
    requests = Request.objects.filter(category__in=categories)
    return render(request, 'main/request_list.html', {'requests': requests})

main/templates/main/change_status.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}
{% load static %}

{% block content %}
  <h2 style="text-align: center; margin-bottom: 20px;">Смена статуса заявки</h2>
  <div style="display: flex; justify-content: center;">
    <div style="max-width: 400px; background-color: #f9f9f9; border: 1px solid #ddd; border-radius: 7px; padding: 20px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div style="margin-bottom: 20px;">
          {{ form.status.label_tag }}
          {{ form.status }}
        </div>
        <div id="comment_field" style="display: none; margin-bottom: 20px;">
          <p style="font-weight: bold;">Комментарий дизайнера:</p>
          {{ form.comment }}
        </div>
        <div id="design_image_field" style="display: none; margin-bottom: 20px;">
          <p style="font-weight: bold;">Готовый дизайн, фото:</p>
          {{ form.design_image }}
        </div>
        <button type="submit" style="width: 100%; padding: 10px; background-color: black; color: white; border: none; border-radius: 5px; cursor: pointer;">Изменить статус</button>
      </form>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="{% static 'js/index.js' %}"></script>
{% endblock %}

main/templates/main/change_user_info.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %} Правка личных данных {% endblock %}

{% block content %}
<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post">
   {% csrf_token %}
   {% bootstrap_form form layout='horizontal' %}
   {% buttons submit='Сохранить' %} {% endbuttons %}
</form>
{% endblock %}

main/templates/main/create_request.html
{% extends "layout/basic.html" %}

{% block content %}
  <h2>Создать заявку</h2>
    <form method="post" enctype="multipart/form-data" style="max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9f9f9; border: 1px solid #ddd; border-radius: 10px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" style="background-color: black; color: white; padding: 20px; border: none; border-radius: 20px; ">Создать заявку</button>
    </form>
{% endblock %}

main/templates/main/delete_request.html
{% extends "layout/basic.html" %}

{% block title %} Удаление заявки {% endblock %}

{% block content %}
<h2>Удаление заявки</h2>
<p>Вы уверены, что хотите удалить заявку "{{ request_obj.title }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Удалить</button>
    <a href="{% url 'main:view_requests' %}">Отмена</a>
</form>
{% endblock %}

main/templates/main/delete_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %} Удаление пользователя {% endblock %}

{% block content %}
<h2>Удаление пользователя {{ object.username }}</h2>
<form method="post">
   {% csrf_token %}
   {% buttons submit='Удалить' %} {% endbuttons %}
</form>
{% endblock %}

main/templates/main/index.html
{% extends "layout/basic.html" %}

{% block title %} Главная {% endblock %}

{% load static %}

{% block content %}
<h2>Количество заявок в статусе «Принято в работу»: {{ in_progress_count }}</h2>
<h2>Последние заявки в статусе «Выполнено»</h2>
<ul style="display: flex; flex-wrap: wrap; justify-content: center; gap: 30px; list-style-type: none; padding: 0;">
    {% for request in completed_requests %}
        <li style="max-width: 400px; background-color: #f9f9f9; border: 1px solid #ddd; border-radius: 7px; margin-top: 30px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);">
            <p><strong>Временная метка:</strong> {{ request.timestamp }}</p>
            <p><strong>Название:</strong> {{ request.title }}</p>
            <p><strong>Категория заявки:</strong> {{ request.category }}</p>
            {% if request.photo %}
                <div class="request-photo-container">
                    <div class="design-text" style="display: none; ">Готовый дизайн</div>
                    <img src="{{ request.photo.url }}" alt="{{ request.title }}" style="max-width: 300px; max-height: 400px; border-radius: 7px; margin-bottom: 10px;" class="request-photo" data-design-image="{% if request.design_image %}{{ request.design_image.url }}{% endif %}">
                </div>
            {% endif %}
            {% if request.design_image %}
                <img src="{{ request.design_image.url }}" alt="{{ request.title }}" style="max-width: 300px; max-height: 400px; border-radius: 7px; margin-bottom: 10px; display: none;" class="design-image">
            {% endif %}
        </li>
    {% endfor %}
</ul>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}

main/templates/main/login.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}
{% load static %}

{% block title %} Вход {% endblock %}

{% block content %}
<h2 style="font-size: 2rem; margin-bottom: 20px;">Вход</h2>

{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post" id="login-form" style="display: flex; max-width: 40vw; height: 60vh; flex-direction: column; padding: 30px 20px;">
    {% csrf_token %}

    <!-- Поля формы -->
    <div class="form-group">
        <label for="id_username" style="font-size: 1.25rem;">Логин:</label>
        <input type="text" id="id_username" name="username" class="form-control" style="border: 2px solid #000; border-radius: 10px; height: 45px;">
    </div>

    <div class="form-group">
        <label for="id_password" style="font-size: 1.25rem;">Пароль:</label>
        <input type="password" id="id_password" name="password" class="form-control" style="border: 2px solid #000; border-radius: 10px; height: 45px;">
    </div>

    <input type="hidden" name="next" value="{{ next }}">
    <input type="submit" value="Войти" style="background-color: black; color: white; padding: 20px; border: none; border-radius: 20px;">
</form>
{% endif %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}

main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %} Выход {% endblock %}

{% block content %}
    <h2>Выход</h2>
    <p>Вы успешно вышли с сайта.</p>
{% endblock %}

main/templates/main/manage_categories.html
{% extends "layout/basic.html" %}

{% block title %} Управление категориями {% endblock %}

{% block content %}
<h2>Управление категориями</h2>
<ul>
    {% for category in categories %}
        <li>
            {{ category.name }}
            <a href="{% url 'main:delete_category' category.id %}" style="color: red;">Удалить</a>
        </li>
    {% endfor %}
</ul>
<h3>Добавить новую категорию</h3>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
</form>
{% endblock %}

main/templates/main/register_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}
{% load static %}

{% block title %} Регистрация {% endblock %}

{% block content %}
<h2>Регистрация нового пользователя</h2>

<form method="post" id="registration-form" style=" display: flex; max-width: 40vw; height: 60vh; flex-direction: column; padding: 30px 20px;">
    {% csrf_token %}

    <!-- Поля формы -->
    <div class="form-group">
        <label for="id_username" style="font-size: 1.25rem;">Логин:</label>
        <input type="text" id="id_username" name="username" class="form-control" onkeyup="check_username(this);" data-url="{% url 'main:check_username' %}" style="border: 2px solid #000; border-radius: 10px; height: 45px;">
        <div id="username-error" style="color: red; display: none;">Имя пользователя занято!</div>
        <div id="username-success" style="color: green; display: none;">Имя пользователя доступно.</div>
    </div>

    <div class="form-group">
        <label for="id_fio" style="font-size: 1.25rem;">ФИО:</label>
        <input type="text" id="id_fio" name="fio" class="form-control" style="border: 2px solid #000; border-radius: 10px; height: 45px;">
        <div id="fio-error" style="color: red; display: none;">ФИО может содержать только кириллические буквы, пробелы и дефисы.</div>
        <div id="fio-error-cyrillic" style="color: red; display: none;">ФИО должно содержать хотя бы одну кириллическую букву.</div>
    </div>

    <div class="form-group">
        <label for="id_email" style="font-size: 1.25rem;">Адрес электронной почты:</label>
        <input type="email" id="id_email" name="email" class="form-control" style="border: 2px solid #000; border-radius: 10px; height: 45px;">
    </div>

    <div class="form-group">
        <label for="id_password1" style="font-size: 1.25rem;">Пароль:</label>
        <input type="password" id="id_password1" name="password1" class="form-control" style="border: 2px solid #000; border-radius: 10px; height: 45px;">
    </div>

    <div class="form-group">
        <label for="id_password2" style="font-size: 1.25rem;">Пароль (повторно):</label>
        <input type="password" id="id_password2" name="password2" class="form-control" style="border: 2px solid #000; border-radius: 10px; height: 45px;">
    </div>

    <div class="form-group form-check">
        <input type="checkbox" id="id_consent" name="consent" class="form-check-input">
        <label for="id_consent" class="form-check-label">Согласие на обработку персональных данных</label>
    </div>

    <input type="submit" value="Зарегистрироваться" style="style="background-color: black; color: white; padding: 20px; border: none; border-radius: 20px;"">
</form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}

main/templates/main/view_requests.html
{% extends "layout/basic.html" %}

{% block title %} Заявки {% endblock %}

{% load static %}

{% block content %}
<h2 style="margin-bottom: 30px">Список заявок</h2>
{% if not user.is_staff %}
    <a href="{% url 'main:create_request' %}" style="background-color: black; color: white; padding: 20px; border: none; border-radius: 20px;">Создать новую заявку</a>
{% endif %}
<ul class="request-list" style="display: flex; flex-wrap: wrap; justify-content: center; gap: 30px; list-style-type: none; padding: 0;">
    {% for request in requests %}
        <li class="request-item" style="max-width: 400px; background-color: #f9f9f9; border: 1px solid #ddd; border-radius: 7px; margin-top: 30px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);" >
            <strong>{{ request.title }}</strong> - {{ request.get_status_display }}
            <p><strong>Описание:</strong>{{ request.description }}</p>
            <p><strong>Категория:</strong> {{ request.category }}</p>
            {% if request.photo %}
                <img src="{{ request.photo.url }}" alt="{{ request.title }}" style="max-width: 300px; max-height: 400px; border-radius: 7px; margin-bottom: 10px;" class="request-photo" data-design-image="{% if request.design_image %}{{ request.design_image.url }}{% endif %}">
            {% endif %}
            <p><strong>Дата создания:</strong>  {{ request.timestamp }}</p>
            {% if request.comment %}
                <p>Комментарий: {{ request.comment }}</p>
            {% endif %}
            {% if request.design_image %}
                <img src="{{ request.design_image.url }}" alt="{{ request.title }}" style="max-width: 300px; max-height: 400px; border-radius: 7px; margin-bottom: 10px; display: none;" class="design-image">
            {% endif %}
            {% if user.is_staff and request.status != 'completed' %}
                <a href="{% url 'main:change_status' request.id %}" style="background-color: black; color: white; padding: 10px; border: none; border-radius: 10px;">Редактировать заявку</a>
            {% endif %}
            {% if not user.is_staff %}
                <a href="{% url 'main:delete_request' request.id %}" style="background-color: black; color: white; padding: 10px; border: none; border-radius: 10px;">Удалить заявку</a>
            {% endif %}
        </li>
    {% endfor %}
</ul>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}